### ISSUE TITLE
When OSC Modulator loads, it loads its previous state

### ISSUE THREAD

**Issue by soulfresh** [OSCModulator/oscmodulator#26]

**Comment by dansomething** [comment]
@soulfresh does this mean we should default to loading the previous "session"? What if one wasn't ever explicitly saved? If so, does that mean there should be some sort of autosave feature?

**Comment by soulfresh** [comment]
Yes, I was thinking we should autosave the current state on close and use that for the next startup. We don't have to do that right now if you want to move onto something else though.

**Comment by dansomething** [comment]
I'm fine working on this. It should be quick now that there's a system for managing sessions in place. 

Here are a few UX options to consider.

1. Autosave on exit
  1. If working with a new "untitled" session then automatically save the session as "$HOME/Documents/OSCModulator/autosave.osc" on app exit.
  1. If working with a session from a file then automatically save the session on app exit.
1. Prompt on exit
  1. If working with a new session that is edited then prompt to save the session on app exit.
    1. If user clicks "continue" then prompt for the file location and save to there.
  1. If working with a session from a file then prompt to save the session on app exit.
    1. If user clicks "continue" then save to current session file name.
1. Hybrid approach (autosave "untitled" sessions, prompt for previously saved sessions)
  1. see option 1.i
  1. see open 2.ii

Let me know what you prefer (option 1, 2, or 3) or if you have another idea or changes to one of these.

**Comment by soulfresh** [comment]
I'd say option 3 would be perfect. Prompting will make sure that we're not saving something that users don't actually want saved.

Sorry for the slow response on this message. Not sure why I missed the emails about it.

**Comment by dansomething** [comment]
No, worries. It has given me the last two weeks to take a break and deal with work being busier.

**Comment by dansomething** [comment]
Closed by merge of #44 into develop.
