### ISSUE TITLE
Protractor E2E errors don't fail the CI job

### ISSUE THREAD

**Issue by dansomething** [OSCModulator/oscmodulator#45]
See the logs in this Travis job. https://travis-ci.org/OSCModulator/oscmodulator/builds/55328809

One test failed, but the job is marked as successful.

**Comment by soulfresh** [comment]
e2e tests have been removed because they were difficult to maintain. I've started creating integration level tests that compile the full application and mock out the file system and legato router. This should be nearly as good and hopefully easier to debug.
