### ISSUE TITLE
Listen to input on multiple midi ports

### ISSUE THREAD

**Issue by soulfresh** [OSCModulator/oscmodulator#53]
Currently listening to more than one midi port (or even changing the midi port) causes the app to crash after several midi events. The issue seems to be an underlying problem in node-midi. We could either look into debugging node-midi or perhaps switch over to another midi library.

Midi Utils JS could be a possible replacement for node-midi:
https://github.com/hhromic/midi-utils-js

Or maybe one of these:
https://www.npmjs.com/browse/keyword/midi

**Comment by dansomething** [comment]
So this is a separate issue from not being able to create more than on instance of node-midi? Do these other Node midi libraries use the same underlying RtMidi C++ library?

**Comment by soulfresh** [comment]
This is the same issue that only allows us to create one instance of node-mid...was there another ticket for it that I missed?

I'm not sure what the other libraries use under the hood.

**Comment by dansomething** [comment]
I don't think there's another ticket unless we already closed it out. I just want the clarification for understanding.

**Comment by soulfresh** [comment]
This actually seems to be fixed with the latest node-midi version! Knock on wood...testing it more this weekend before I close this ticket.

**Comment by soulfresh** [comment]
I think this is still an issue. Going to look into upgrading NW.js in order to take advantage of native browser midi.

**Comment by soulfresh** [comment]
This works after the upgrade to the latest NW.js.
